import type { Metadata } from "next";
import { Geist, Geist_Mono, Comforter } from "next/font/google";
import "./globals.css";
// import Header from "@/components/Header";



import Link from "next/link";

const comforter = Comforter({
  variable: "--font-comforter",
  subsets: ["latin"],
  weight: "400"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comforter.variable} ${geistMono.variable} antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
